name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      API_URL: http://localhost:3000
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Test
        run: pnpm run test
